### ISSUE TITLE
Allow to serialize case class with single field in js object

### ISSUE THREAD

**Issue by Tims101** [fomkin/pushka#15]
Hi.

How can I serialize case object with one field to js object. 

Now, If I make this:

``` scala
@pushka
case class User(name: String)

write(User("tims101")) 
```

I'll have 

``` json
"tims101"
```

but I want to have this 

``` json
{"name": "tims101"}
```

**Comment by fomkin** [comment]
@Tims101 Hi. 0.6.0 will be released in few days. Starting this version you can use `@forceObject` for this case.
