### ISSUE TITLE
Rewriting field Names with Annotations

### ISSUE THREAD

**Issue by schmitch** [fomkin/pushka#20]
Hello, it would be great if pushka have something like rewriting field names with Annotations.

Currently I try to consume some JSON from logstash which have some aweful keys:

```
{"@timestamp": "...", "message", "", ..}
```

It would be great if I could have a case class like that which would work

```
@pushka
 case class(@Name("@timestamp") timestamp: String, message: String)
```

So I could consume even "bad behaved" things.

**Comment by fomkin** [comment]
Ok. Seems like simple to implement.

**Comment by schmitch** [comment]
@fomkin I think there should also be a global option where some could have a naming scheme.
Mostly people will write firstName in scala while people prefer first_name in javascript.

**Comment by fomkin** [comment]
Good idea. Could you create new issue for it?

**Comment by schmitch** [comment]
yeah
