### ISSUE TITLE
Support for sealed trait with mixins

### ISSUE THREAD

**Issue by zv3** [fomkin/pushka#23]
I'm trying to serialize a trait that mixes with some other traits and seems to work quite fine if i try to read/write from the child trait, but when I try to `json.read(..)` or `json.write(..)` an instance from the root trait it throws a `pushka.package$PushkaException`

```
@pushka
sealed trait Foo

object Foo

@pushka
sealed trait Bar extends Foo 

object Bar {
  case class A(a: String) extends Bar
}

val test: Bar = A("a")
write(test) // works fine

val test: Foo = A("a")
write(test) // throws an exception on runtime
```

Tried to implement a custom serializer using pattern matching but i didn't know how to get an `AST` result from an implicit writer.

Great work btw, I got into this project looking for a more natural JSON output from a scalajs pickler library.

**Comment by fomkin** [comment]
> I'm trying to serialize a trait that mixes with some other traits

For now writer of `Foo` doesn't know about subclasses of `Bar`.

> Tried to implement a custom serializer using pattern matching but i didn't know how to get an AST result from an implicit writer.

Use `pushka.write` and `pushka.read` instead of `pushka.json.*`.

**Comment by zv3** [comment]
Will give it a try, appreciate it.
