### ISSUE TITLE
Mixing annotation

### ISSUE THREAD

**Issue by sergP80** [fomkin/pushka#42]
I have one question. Is it possible to mix @pushka for classes those are in third-party library? For example, third-party.jar has class Response and I want to parse it into JSON. How can I do it? If it's possible please add this info into Readme. Thanks.

**Comment by fomkin** [comment]
No, now it's not possible. Pushka designed to work with raw Scala AST, not with reflection.

**Comment by sergP80** [comment]
Thanks for replay. May be, in the further versions you will add this feature. It will be very useful.

**Comment by sergP80** [comment]
Ok, and I have one else question. Is it the best way to parsing Exception to/from json using library? Thanks.

**Comment by pushka** [comment]
Yeah - I'll push it tomorrow

**Comment by fomkin** [comment]
> Ok, and I have one else question. Is it the best way to parsing Exception to/from json using library? Thanks.

I recommend to use `Either` instead `Exception`.

``` scala
val result = try {
  Right(100)
} catch {
  case e: Throwable =>
    Left(e.getMessage)
}
write(result)
```

``` json
{ "right": 100 }
```

``` json
{ "left": "Your error message" }
```

**Comment by sergP80** [comment]
Ok, thanks for your help. I'm waiting updates for mixing )). By and good luck.
